//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiatek.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotations() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asiatek.Resource.DataAnnotations", typeof(DataAnnotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前动作已经绑定过功能 的本地化字符串。
        /// </summary>
        public static string ActionIDHadBeenLinkedWithFunction {
            get {
                return ResourceManager.GetString("ActionIDHadBeenLinkedWithFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同控制器下已存在同名动作！ 的本地化字符串。
        /// </summary>
        public static string ActionNameExists {
            get {
                return ResourceManager.GetString("ActionNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须以大写字母开头，特殊字符只能包含下划线 的本地化字符串。
        /// </summary>
        public static string AreaControllerActionName {
            get {
                return ResourceManager.GetString("AreaControllerActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主终端与辅助终端重复！ 的本地化字符串。
        /// </summary>
        public static string AuxiliaryTerminalIDError {
            get {
                return ResourceManager.GetString("AuxiliaryTerminalIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经绑定车辆无法修改！ 的本地化字符串。
        /// </summary>
        public static string BindVehicleNoEdit {
            get {
                return ResourceManager.GetString("BindVehicleNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型为押运员的员工已关联相关车辆，不能取消选择押运员！ 的本地化字符串。
        /// </summary>
        public static string CarrierError {
            get {
                return ResourceManager.GetString("CarrierError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车籍地必输输入6位纯数字！ 的本地化字符串。
        /// </summary>
        public static string CarToLandError {
            get {
                return ResourceManager.GetString("CarToLandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码格式有误！ 的本地化字符串。
        /// </summary>
        public static string ChinesePhoneError {
            get {
                return ResourceManager.GetString("ChinesePhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码与新密码输入不一致！ 的本地化字符串。
        /// </summary>
        public static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同区域下已存在同名控制器！ 的本地化字符串。
        /// </summary>
        public static string ControllerNameExists {
            get {
                return ResourceManager.GetString("ControllerNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期格式有误，只能是 年-月-日 的本地化字符串。
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期格式有误，只能是 年-月-日 时:分:秒 的本地化字符串。
        /// </summary>
        public static string DateTimeError {
            get {
                return ResourceManager.GetString("DateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前环境不支持 Canvas！ 的本地化字符串。
        /// </summary>
        public static string DoNotSupportCanvas {
            get {
                return ResourceManager.GetString("DoNotSupportCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制电子围栏区域 的本地化字符串。
        /// </summary>
        public static string DrawEFArea {
            get {
                return ResourceManager.GetString("DrawEFArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型为驾驶员的员工已关联相关车辆，不能取消选择驾驶员！ 的本地化字符串。
        /// </summary>
        public static string DriverError {
            get {
                return ResourceManager.GetString("DriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的邮箱格式！ 的本地化字符串。
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择员工类型！ 的本地化字符串。
        /// </summary>
        public static string EmployeeTypeError {
            get {
                return ResourceManager.GetString("EmployeeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间不能大于当前时间 的本地化字符串。
        /// </summary>
        public static string EndTimeRangeOverNow {
            get {
                return ResourceManager.GetString("EndTimeRangeOverNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已存在！ 的本地化字符串。
        /// </summary>
        public static string FieldExists {
            get {
                return ResourceManager.GetString("FieldExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在！ 的本地化字符串。
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初次保养里程请输入数字！ 的本地化字符串。
        /// </summary>
        public static string FirstMaintenanceMilePleaseInputNum {
            get {
                return ResourceManager.GetString("FirstMaintenanceMilePleaseInputNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号格式有误！ 的本地化字符串。
        /// </summary>
        public static string IDcardError {
            get {
                return ResourceManager.GetString("IDcardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号不能重复！ 的本地化字符串。
        /// </summary>
        public static string IDCardIsExist {
            get {
                return ResourceManager.GetString("IDCardIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限速选中时，最高速度和超速持续时间必填！ 的本地化字符串。
        /// </summary>
        public static string IsCheckSpeedMustInput {
            get {
                return ResourceManager.GetString("IsCheckSpeedMustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判断行驶时间选中时，路段行驶过长和路段行驶不足必填！ 的本地化字符串。
        /// </summary>
        public static string IsCheckTimeMustInput {
            get {
                return ResourceManager.GetString("IsCheckTimeMustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业户经营许可证号为12位纯数字且不能以0开头！ 的本地化字符串。
        /// </summary>
        public static string LicenseNoError {
            get {
                return ResourceManager.GetString("LicenseNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司Logo最大1M！ 的本地化字符串。
        /// </summary>
        public static string LogoSizeError {
            get {
                return ResourceManager.GetString("LogoSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo类型只能是jpg或png！ 的本地化字符串。
        /// </summary>
        public static string LogoTypeError {
            get {
                return ResourceManager.GetString("LogoTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车载终端厂商编码只能是5位纯数字！ 的本地化字符串。
        /// </summary>
        public static string ManufacturerCodeError {
            get {
                return ResourceManager.GetString("ManufacturerCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的最大长度为{1}个字符！ 的本地化字符串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的长度在{1}到{2} 的本地化字符串。
        /// </summary>
        public static string MaxMinLength {
            get {
                return ResourceManager.GetString("MaxMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}最多为三位整数！ 的本地化字符串。
        /// </summary>
        public static string MustBeThreeIntegers {
            get {
                return ResourceManager.GetString("MustBeThreeIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须输入{0}！ 的本地化字符串。
        /// </summary>
        public static string MustInput {
            get {
                return ResourceManager.GetString("MustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须输入驾驶证有效期！ 的本地化字符串。
        /// </summary>
        public static string MustInputDriveCodeValidTime {
            get {
                return ResourceManager.GetString("MustInputDriveCodeValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须输入驾照状态！ 的本地化字符串。
        /// </summary>
        public static string MustInputDriveLicenseStateID {
            get {
                return ResourceManager.GetString("MustInputDriveLicenseStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须输入准驾车型！ 的本地化字符串。
        /// </summary>
        public static string MustInputDriveTypeID {
            get {
                return ResourceManager.GetString("MustInputDriveTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择{0}！ 的本地化字符串。
        /// </summary>
        public static string MustSelect {
            get {
                return ResourceManager.GetString("MustSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择一个动作方法！ 的本地化字符串。
        /// </summary>
        public static string MustSelectAction {
            get {
                return ResourceManager.GetString("MustSelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少选择一个功能！ 的本地化字符串。
        /// </summary>
        public static string MustSelectAtLeastOneFunction {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择定位终端！ 的本地化字符串。
        /// </summary>
        public static string MustSelectPrimaryTerminal {
            get {
                return ResourceManager.GetString("MustSelectPrimaryTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行政区划码只能是6位纯数字！ 的本地化字符串。
        /// </summary>
        public static string NationalityCodeError {
            get {
                return ResourceManager.GetString("NationalityCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工为押运员时，押运员证有效期必须输入！ 的本地化字符串。
        /// </summary>
        public static string NeedCarrieCodeValidTime {
            get {
                return ResourceManager.GetString("NeedCarrieCodeValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工为押运员时，押运员资格证必须输入！ 的本地化字符串。
        /// </summary>
        public static string NeedCarrierCode {
            get {
                return ResourceManager.GetString("NeedCarrierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先绘制图形，然后提交！ 的本地化字符串。
        /// </summary>
        public static string NeedDrawError {
            get {
                return ResourceManager.GetString("NeedDrawError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先绘制路线，确认后再提交！ 的本地化字符串。
        /// </summary>
        public static string NeedDrawLineError {
            get {
                return ResourceManager.GetString("NeedDrawLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工为驾驶员时，驾驶证号必须输入！ 的本地化字符串。
        /// </summary>
        public static string NeedDriveCode {
            get {
                return ResourceManager.GetString("NeedDriveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工为驾驶员时，驾驶证有效期必须输入！ 的本地化字符串。
        /// </summary>
        public static string NeedDriveCodeValidTime {
            get {
                return ResourceManager.GetString("NeedDriveCodeValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工为押运员时，紧急电话必须输入！ 的本地化字符串。
        /// </summary>
        public static string NeedEmergePhone {
            get {
                return ResourceManager.GetString("NeedEmergePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不可以与原密码相同！ 的本地化字符串。
        /// </summary>
        public static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不应小于 的本地化字符串。
        /// </summary>
        public static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量和单价是数字！ 的本地化字符串。
        /// </summary>
        public static string NumAndUnitPriceMustNumber {
            get {
                return ResourceManager.GetString("NumAndUnitPriceMustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择一个驾驶员！ 的本地化字符串。
        /// </summary>
        public static string OnlyOneDriver {
            get {
                return ResourceManager.GetString("OnlyOneDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择一个押运员！ 的本地化字符串。
        /// </summary>
        public static string OnlyOneEscort {
            get {
                return ResourceManager.GetString("OnlyOneEscort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码输入不正确！ 的本地化字符串。
        /// </summary>
        public static string OriginalPasswordError {
            get {
                return ResourceManager.GetString("OriginalPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多输入2个纯汉字！ 的本地化字符串。
        /// </summary>
        public static string PlateColor {
            get {
                return ResourceManager.GetString("PlateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号长度为7位或8位！ 的本地化字符串。
        /// </summary>
        public static string PlateNumLengthError {
            get {
                return ResourceManager.GetString("PlateNumLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一种报警类型！ 的本地化字符串。
        /// </summary>
        public static string PleaseChooseOneAlarmType {
            get {
                return ResourceManager.GetString("PleaseChooseOneAlarmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择周期！ 的本地化字符串。
        /// </summary>
        public static string PleaseChooseWeekFirst {
            get {
                return ResourceManager.GetString("PleaseChooseWeekFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先绘制图形电子围栏！ 的本地化字符串。
        /// </summary>
        public static string PleaseDrawElectricFenceFirst {
            get {
                return ResourceManager.GetString("PleaseDrawElectricFenceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先鼠标右击新增电子围栏 的本地化字符串。
        /// </summary>
        public static string PleaseFirstRightClickAddEF {
            get {
                return ResourceManager.GetString("PleaseFirstRightClickAddEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入周期设置信息！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputCycleSettingInfo {
            get {
                return ResourceManager.GetString("PleaseInputCycleSettingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入上次保养里程和上次保养时间信息！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputLastMaintenanceMileAndTimeFirst {
            get {
                return ResourceManager.GetString("PleaseInputLastMaintenanceMileAndTimeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入保养项目！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputMaintenanceProjectDetails {
            get {
                return ResourceManager.GetString("PleaseInputMaintenanceProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入限速值！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputMaxSpeedFirst {
            get {
                return ResourceManager.GetString("PleaseInputMaxSpeedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入查询条件! 的本地化字符串。
        /// </summary>
        public static string PleaseInputSearchInfoFirst {
            get {
                return ResourceManager.GetString("PleaseInputSearchInfoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入周期时间！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputTimeFirst {
            get {
                return ResourceManager.GetString("PleaseInputTimeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入预计卸货时长！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputUnLoadTimeFirst {
            get {
                return ResourceManager.GetString("PleaseInputUnLoadTimeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入车辆代号选择一条记录! 的本地化字符串。
        /// </summary>
        public static string PleaseInputVehicleNameFirst {
            get {
                return ResourceManager.GetString("PleaseInputVehicleNameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先查询记录! 的本地化字符串。
        /// </summary>
        public static string PleaseSearchFirst {
            get {
                return ResourceManager.GetString("PleaseSearchFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择查询时间！ 的本地化字符串。
        /// </summary>
        public static string PleaseSelectSearchTime {
            get {
                return ResourceManager.GetString("PleaseSelectSearchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须为正整数！ 的本地化字符串。
        /// </summary>
        public static string PositiveIntegerError {
            get {
                return ResourceManager.GetString("PositiveIntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}范围在{1}到{2} 的本地化字符串。
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色至少得包含一个功能！ 的本地化字符串。
        /// </summary>
        public static string RoleMustHaveOneFunction {
            get {
                return ResourceManager.GetString("RoleMustHaveOneFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前查询结果没有温度数据！ 的本地化字符串。
        /// </summary>
        public static string SearchResultWithNoTemperData {
            get {
                return ResourceManager.GetString("SearchResultWithNoTemperData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此次查询无返回结果！ 的本地化字符串。
        /// </summary>
        public static string SearchReturnNoData {
            get {
                return ResourceManager.GetString("SearchReturnNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 里程周期和时间周期设置需要输入整数！ 的本地化字符串。
        /// </summary>
        public static string SettingMileAndSettingDayPleaseInputInteger {
            get {
                return ResourceManager.GetString("SettingMileAndSettingDayPleaseInputInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SIM卡号为11位或13位纯数字！ 的本地化字符串。
        /// </summary>
        public static string SIMCodeError {
            get {
                return ResourceManager.GetString("SIMCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间不可以大于结束时间！ 的本地化字符串。
        /// </summary>
        public static string StartTimeMoreThanEndTimeError {
            get {
                return ResourceManager.GetString("StartTimeMoreThanEndTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间不能小于结束时间6个月以上！ 的本地化字符串。
        /// </summary>
        public static string StartTimeRangeOver6Months {
            get {
                return ResourceManager.GetString("StartTimeRangeOver6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多4个手机号，采用半角;分割！ 的本地化字符串。
        /// </summary>
        public static string StructureMobilesError {
            get {
                return ResourceManager.GetString("StructureMobilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择一种地图类型！ 的本地化字符串。
        /// </summary>
        public static string StructureMustSelectMapType {
            get {
                return ResourceManager.GetString("StructureMustSelectMapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 然后点击右上角工具 的本地化字符串。
        /// </summary>
        public static string ThenClickTopRightTool {
            get {
                return ResourceManager.GetString("ThenClickTopRightTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期要小于截止日期、区间不能大于30天！ 的本地化字符串。
        /// </summary>
        public static string TimeInterval {
            get {
                return ResourceManager.GetString("TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间跨度不可以超过2个月 的本地化字符串。
        /// </summary>
        public static string TimeRangeOver2Months {
            get {
                return ResourceManager.GetString("TimeRangeOver2Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间间隔设置错误 的本地化字符串。
        /// </summary>
        public static string TimeSpanError {
            get {
                return ResourceManager.GetString("TimeSpanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间间隔必须为大于等于2的正整数 的本地化字符串。
        /// </summary>
        public static string TimespanMust {
            get {
                return ResourceManager.GetString("TimespanMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间间隔只能是正整数 的本地化字符串。
        /// </summary>
        public static string TimeSpanNum {
            get {
                return ResourceManager.GetString("TimeSpanNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户下没有数据！ 的本地化字符串。
        /// </summary>
        public static string UserReturnNoData {
            get {
                return ResourceManager.GetString("UserReturnNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码输入错误！ 的本地化字符串。
        /// </summary>
        public static string ValidateCodeError {
            get {
                return ResourceManager.GetString("ValidateCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值只能是数字！ 的本地化字符串。
        /// </summary>
        public static string ValueIsNum {
            get {
                return ResourceManager.GetString("ValueIsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择车辆 的本地化字符串。
        /// </summary>
        public static string VehicleMustCheck {
            get {
                return ResourceManager.GetString("VehicleMustCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前使用单位下已存在相同的车代号！ 的本地化字符串。
        /// </summary>
        public static string VehicleNameExists {
            get {
                return ResourceManager.GetString("VehicleNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个车辆不能重复设置相同的传感器 的本地化字符串。
        /// </summary>
        public static string VehicleSensorSetError {
            get {
                return ResourceManager.GetString("VehicleSensorSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多输入10个纯汉字！ 的本地化字符串。
        /// </summary>
        public static string VehicleTName {
            get {
                return ResourceManager.GetString("VehicleTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车架号为17位数字和字母组合！ 的本地化字符串。
        /// </summary>
        public static string VINError {
            get {
                return ResourceManager.GetString("VINError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须大于等于{1} 的本地化字符串。
        /// </summary>
        public static string WarrantyDateError {
            get {
                return ResourceManager.GetString("WarrantyDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的文件格式！ 的本地化字符串。
        /// </summary>
        public static string WrongFileType {
            get {
                return ResourceManager.GetString("WrongFileType", resourceCulture);
            }
        }
    }
}
