//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiatek.TMS.PlatformServicesNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatformServicesNS.PlatformServicesSoap")]
    public interface PlatformServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 replyContent 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReplyInspectionMessage", ReplyAction="*")]
        Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponse ReplyInspectionMessage(Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReplyInspectionMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponse> ReplyInspectionMessageAsync(Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplyInspectionMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReplyInspectionMessage", Namespace="http://tempuri.org/", Order=0)]
        public Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequestBody Body;
        
        public ReplyInspectionMessageRequest() {
        }
        
        public ReplyInspectionMessageRequest(Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplyInspectionMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint msgID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string replyContent;
        
        public ReplyInspectionMessageRequestBody() {
        }
        
        public ReplyInspectionMessageRequestBody(uint msgID, string replyContent) {
            this.msgID = msgID;
            this.replyContent = replyContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplyInspectionMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReplyInspectionMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponseBody Body;
        
        public ReplyInspectionMessageResponse() {
        }
        
        public ReplyInspectionMessageResponse(Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplyInspectionMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReplyInspectionMessageResult;
        
        public ReplyInspectionMessageResponseBody() {
        }
        
        public ReplyInspectionMessageResponseBody(int ReplyInspectionMessageResult) {
            this.ReplyInspectionMessageResult = ReplyInspectionMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlatformServicesSoapChannel : Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatformServicesSoapClient : System.ServiceModel.ClientBase<Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap>, Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap {
        
        public PlatformServicesSoapClient() {
        }
        
        public PlatformServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatformServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponse Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap.ReplyInspectionMessage(Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest request) {
            return base.Channel.ReplyInspectionMessage(request);
        }
        
        public int ReplyInspectionMessage(uint msgID, string replyContent) {
            Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest inValue = new Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest();
            inValue.Body = new Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequestBody();
            inValue.Body.msgID = msgID;
            inValue.Body.replyContent = replyContent;
            Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponse retVal = ((Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap)(this)).ReplyInspectionMessage(inValue);
            return retVal.Body.ReplyInspectionMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponse> Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap.ReplyInspectionMessageAsync(Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest request) {
            return base.Channel.ReplyInspectionMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageResponse> ReplyInspectionMessageAsync(uint msgID, string replyContent) {
            Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest inValue = new Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequest();
            inValue.Body = new Asiatek.TMS.PlatformServicesNS.ReplyInspectionMessageRequestBody();
            inValue.Body.msgID = msgID;
            inValue.Body.replyContent = replyContent;
            return ((Asiatek.TMS.PlatformServicesNS.PlatformServicesSoap)(this)).ReplyInspectionMessageAsync(inValue);
        }
    }
}
