//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiatek.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asiatek.Resource.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 异常轨迹 的本地化字符串。
        /// </summary>
        public static string AbnormalTrack {
            get {
                return ResourceManager.GetString("AbnormalTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加子单位 的本地化字符串。
        /// </summary>
        public static string AddSubStruc {
            get {
                return ResourceManager.GetString("AddSubStruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配 的本地化字符串。
        /// </summary>
        public static string AllotButton {
            get {
                return ResourceManager.GetString("AllotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同时删除绑定的车辆信息！ 的本地化字符串。
        /// </summary>
        public static string AlsoDeleteBindVehicleInfo {
            get {
                return ResourceManager.GetString("AlsoDeleteBindVehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域超速 的本地化字符串。
        /// </summary>
        public static string AreaOverSpeed {
            get {
                return ResourceManager.GetString("AreaOverSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string Audite {
            get {
                return ResourceManager.GetString("Audite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份服务器IP地址或域名 的本地化字符串。
        /// </summary>
        public static string BackupServerIP {
            get {
                return ResourceManager.GetString("BackupServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下发中... 的本地化字符串。
        /// </summary>
        public static string BeingProcessed {
            get {
                return ResourceManager.GetString("BeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定车辆 的本地化字符串。
        /// </summary>
        public static string BindVehicle {
            get {
                return ResourceManager.GetString("BindVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车必须选择经营范围！ 的本地化字符串。
        /// </summary>
        public static string BusinessScopeError {
            get {
                return ResourceManager.GetString("BusinessScopeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选择 的本地化字符串。
        /// </summary>
        public static string CancelSelect {
            get {
                return ResourceManager.GetString("CancelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车必须选择押运员！ 的本地化字符串。
        /// </summary>
        public static string CarrierError {
            get {
                return ResourceManager.GetString("CarrierError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车必须输入车籍地！ 的本地化字符串。
        /// </summary>
        public static string CarToLandError {
            get {
                return ResourceManager.GetString("CarToLandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击更换验证码 的本地化字符串。
        /// </summary>
        public static string ChangeValidateCode {
            get {
                return ResourceManager.GetString("ChangeValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控车辆 的本地化字符串。
        /// </summary>
        public static string CheckedVehicles {
            get {
                return ResourceManager.GetString("CheckedVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆形 的本地化字符串。
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭接入 的本地化字符串。
        /// </summary>
        public static string CloseAccessButton {
            get {
                return ResourceManager.GetString("CloseAccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭夜间禁行分析 的本地化字符串。
        /// </summary>
        public static string CloseNightban {
            get {
                return ResourceManager.GetString("CloseNightban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭转发 的本地化字符串。
        /// </summary>
        public static string CloseTransmitButton {
            get {
                return ResourceManager.GetString("CloseTransmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少配置一个温度传感器! 的本地化字符串。
        /// </summary>
        public static string ConfigureAtLeastOneTemperatureSensor {
            get {
                return ResourceManager.GetString("ConfigureAtLeastOneTemperatureSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认添加车辆到当前电子围栏吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmAddVehicleToEF {
            get {
                return ResourceManager.GetString("ConfirmAddVehicleToEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定分配吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmAllot {
            get {
                return ResourceManager.GetString("ConfirmAllot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认分配经营范围吗? 的本地化字符串。
        /// </summary>
        public static string ConfirmBusinessScope {
            get {
                return ResourceManager.GetString("ConfirmBusinessScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认关闭接入吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmCloseAccess {
            get {
                return ResourceManager.GetString("ConfirmCloseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认关闭转发吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmCloseTransmit {
            get {
                return ResourceManager.GetString("ConfirmCloseTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认处理吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmDeal {
            get {
                return ResourceManager.GetString("ConfirmDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认禁用信号接收吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmDisableReceive {
            get {
                return ResourceManager.GetString("ConfirmDisableReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认启用信号接收吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmEnableReceive {
            get {
                return ResourceManager.GetString("ConfirmEnableReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认修改吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmModify {
            get {
                return ResourceManager.GetString("ConfirmModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认开启接入吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmOpenAccess {
            get {
                return ResourceManager.GetString("ConfirmOpenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认开启转发吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmOpenTransmit {
            get {
                return ResourceManager.GetString("ConfirmOpenTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认回复吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmReply {
            get {
                return ResourceManager.GetString("ConfirmReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认重置吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmResetPwd {
            get {
                return ResourceManager.GetString("ConfirmResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认报废吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmScrap {
            get {
                return ResourceManager.GetString("ConfirmScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认发送吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmSend {
            get {
                return ResourceManager.GetString("ConfirmSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认切换为用户{0}吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmSwitchUser {
            get {
                return ResourceManager.GetString("ConfirmSwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认分配运输行业吗? 的本地化字符串。
        /// </summary>
        public static string ConfirmTransportIndustry {
            get {
                return ResourceManager.GetString("ConfirmTransportIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认解绑当前车辆吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmUnBindVehicle {
            get {
                return ResourceManager.GetString("ConfirmUnBindVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入控制器名称 的本地化字符串。
        /// </summary>
        public static string ControllerNamePlaceHolder {
            get {
                return ResourceManager.GetString("ControllerNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 的本地化字符串。
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理紧急报警 的本地化字符串。
        /// </summary>
        public static string DealEmergencyAlarm {
            get {
                return ResourceManager.GetString("DealEmergencyAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认模式 的本地化字符串。
        /// </summary>
        public static string DefaultMode {
            get {
                return ResourceManager.GetString("DefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇鎏车辆动态管理系统 的本地化字符串。
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string DisableButton {
            get {
                return ResourceManager.GetString("DisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配经营范围 的本地化字符串。
        /// </summary>
        public static string DistributionBusinessScope {
            get {
                return ResourceManager.GetString("DistributionBusinessScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配运输行业 的本地化字符串。
        /// </summary>
        public static string DistributionTransportIndustry {
            get {
                return ResourceManager.GetString("DistributionTransportIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖动下方横线可以调整信息列表高度！ 的本地化字符串。
        /// </summary>
        public static string DragChangeSize {
            get {
                return ResourceManager.GetString("DragChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制 的本地化字符串。
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驶入 的本地化字符串。
        /// </summary>
        public static string DriveIn {
            get {
                return ResourceManager.GetString("DriveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驶出 的本地化字符串。
        /// </summary>
        public static string DriveOut {
            get {
                return ResourceManager.GetString("DriveOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驾驶员 的本地化字符串。
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车必须选择驾驶员！ 的本地化字符串。
        /// </summary>
        public static string DriverError {
            get {
                return ResourceManager.GetString("DriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 东 的本地化字符串。
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *已处理，等待终端结果 的本地化字符串。
        /// </summary>
        public static string EmergencyAlarmExtraInfo1 {
            get {
                return ResourceManager.GetString("EmergencyAlarmExtraInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *处理超时，建议30秒后重试 的本地化字符串。
        /// </summary>
        public static string EmergencyAlarmExtraInfo2 {
            get {
                return ResourceManager.GetString("EmergencyAlarmExtraInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急报警 的本地化字符串。
        /// </summary>
        public static string EmergencyAlarms {
            get {
                return ResourceManager.GetString("EmergencyAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工类型 的本地化字符串。
        /// </summary>
        public static string EmployeeType {
            get {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string EmptyFunctionName {
            get {
                return ResourceManager.GetString("EmptyFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string EnableButton {
            get {
                return ResourceManager.GetString("EnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误,请联系管理员！ 的本地化字符串。
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 押运员 的本地化字符串。
        /// </summary>
        public static string Escort {
            get {
                return ResourceManager.GetString("Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常结束地址 的本地化字符串。
        /// </summary>
        public static string ExceptionEndAddress {
            get {
                return ResourceManager.GetString("ExceptionEndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常结束时间 的本地化字符串。
        /// </summary>
        public static string ExceptionEndDateTime {
            get {
                return ResourceManager.GetString("ExceptionEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常通知音 的本地化字符串。
        /// </summary>
        public static string ExceptionNoticeSound {
            get {
                return ResourceManager.GetString("ExceptionNoticeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常提醒类型 的本地化字符串。
        /// </summary>
        public static string ExNoticeType {
            get {
                return ResourceManager.GetString("ExNoticeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Excel 的本地化字符串。
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出权限内车辆列表 的本地化字符串。
        /// </summary>
        public static string ExportExcelWithenAuth {
            get {
                return ResourceManager.GetString("ExportExcelWithenAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已结束 的本地化字符串。
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁入 的本地化字符串。
        /// </summary>
        public static string ForbidIn {
            get {
                return ResourceManager.GetString("ForbidIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁出 的本地化字符串。
        /// </summary>
        public static string ForbidOut {
            get {
                return ResourceManager.GetString("ForbidOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由模式 的本地化字符串。
        /// </summary>
        public static string FreeMode {
            get {
                return ResourceManager.GetString("FreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审核 的本地化字符串。
        /// </summary>
        public static string HasAudite {
            get {
                return ResourceManager.GetString("HasAudite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏报警信息 的本地化字符串。
        /// </summary>
        public static string HideAlarmInfo {
            get {
                return ResourceManager.GetString("HideAlarmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏卸料列表 的本地化字符串。
        /// </summary>
        public static string HidePressureTable {
            get {
                return ResourceManager.GetString("HidePressureTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏信号列表 的本地化字符串。
        /// </summary>
        public static string HideSignalsList {
            get {
                return ResourceManager.GetString("HideSignalsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏停车点列表 的本地化字符串。
        /// </summary>
        public static string HideStopContentTable {
            get {
                return ResourceManager.GetString("HideStopContentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏温度曲线图 的本地化字符串。
        /// </summary>
        public static string HideTemperTable {
            get {
                return ResourceManager.GetString("HideTemperTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Excel 的本地化字符串。
        /// </summary>
        public static string ImportExcel {
            get {
                return ResourceManager.GetString("ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查岗信息 的本地化字符串。
        /// </summary>
        public static string Inspections {
            get {
                return ResourceManager.GetString("Inspections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查岗提醒类型 的本地化字符串。
        /// </summary>
        public static string InspectType {
            get {
                return ResourceManager.GetString("InspectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域车辆 的本地化字符串。
        /// </summary>
        public static string IntraScopeVehicles {
            get {
                return ResourceManager.GetString("IntraScopeVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已同步 的本地化字符串。
        /// </summary>
        public static string IsSynchroed {
            get {
                return ResourceManager.GetString("IsSynchroed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留输入 的本地化字符串。
        /// </summary>
        public static string KeepEnteredContent {
            get {
                return ResourceManager.GetString("KeepEnteredContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌颜色 的本地化字符串。
        /// </summary>
        public static string LicensePlateColor {
            get {
                return ResourceManager.GetString("LicensePlateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传png/jpg格式的图片 的本地化字符串。
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保养预警 的本地化字符串。
        /// </summary>
        public static string MaintenanceCheckAlarm {
            get {
                return ResourceManager.GetString("MaintenanceCheckAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保养记录 的本地化字符串。
        /// </summary>
        public static string MaintenanceRecord {
            get {
                return ResourceManager.GetString("MaintenanceRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保养方案 的本地化字符串。
        /// </summary>
        public static string MaintenanceSchedule {
            get {
                return ResourceManager.GetString("MaintenanceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图类型 的本地化字符串。
        /// </summary>
        public static string MapType {
            get {
                return ResourceManager.GetString("MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 里程或时间周期 的本地化字符串。
        /// </summary>
        public static string MileageAndTimePeriod {
            get {
                return ResourceManager.GetString("MileageAndTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 里程周期 的本地化字符串。
        /// </summary>
        public static string MileagePeriod {
            get {
                return ResourceManager.GetString("MileagePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改限速值 的本地化字符串。
        /// </summary>
        public static string ModifySpeedLimitButton {
            get {
                return ResourceManager.GetString("ModifySpeedLimitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改保固期 的本地化字符串。
        /// </summary>
        public static string ModifyWarrantyDateButton {
            get {
                return ResourceManager.GetString("ModifyWarrantyDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公安交通管理部门颁发的机动车号牌 的本地化字符串。
        /// </summary>
        public static string MotorNumberPlate {
            get {
                return ResourceManager.GetString("MotorNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须按照顺序配置! 的本地化字符串。
        /// </summary>
        public static string MustBeConfiguredInOrder {
            get {
                return ResourceManager.GetString("MustBeConfiguredInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的紧急报警消息！ 的本地化字符串。
        /// </summary>
        public static string NewEmergencyAlarm {
            get {
                return ResourceManager.GetString("NewEmergencyAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的查岗消息！ 的本地化字符串。
        /// </summary>
        public static string NewInspectionInfo {
            get {
                return ResourceManager.GetString("NewInspectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南钢嘉华 的本地化字符串。
        /// </summary>
        public static string NGJH {
            get {
                return ResourceManager.GetString("NGJH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入昵称 的本地化字符串。
        /// </summary>
        public static string NickNamePlaceHolder {
            get {
                return ResourceManager.GetString("NickNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂未分配经营范围 的本地化字符串。
        /// </summary>
        public static string NoBusinessScope {
            get {
                return ResourceManager.GetString("NoBusinessScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查无数据！ 的本地化字符串。
        /// </summary>
        public static string NoDatas {
            get {
                return ResourceManager.GetString("NoDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权限! 的本地化字符串。
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北 的本地化字符串。
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 东北 的本地化字符串。
        /// </summary>
        public static string NorthEast {
            get {
                return ResourceManager.GetString("NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西北 的本地化字符串。
        /// </summary>
        public static string NorthWest {
            get {
                return ResourceManager.GetString("NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未同步 的本地化字符串。
        /// </summary>
        public static string NoSynchro {
            get {
                return ResourceManager.GetString("NoSynchro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未审核 的本地化字符串。
        /// </summary>
        public static string NotAudite {
            get {
                return ResourceManager.GetString("NotAudite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string Noting {
            get {
                return ResourceManager.GetString("Noting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂未分配运输行业 的本地化字符串。
        /// </summary>
        public static string NoTransportIndustry {
            get {
                return ResourceManager.GetString("NoTransportIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不在用客户 的本地化字符串。
        /// </summary>
        public static string NoUseCustomer {
            get {
                return ResourceManager.GetString("NoUseCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在 的本地化字符串。
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掉线 的本地化字符串。
        /// </summary>
        public static string OfflineStatus {
            get {
                return ResourceManager.GetString("OfflineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启接入 的本地化字符串。
        /// </summary>
        public static string OpenAccessButton {
            get {
                return ResourceManager.GetString("OpenAccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用夜间禁行分析 的本地化字符串。
        /// </summary>
        public static string OpenNightban {
            get {
                return ResourceManager.GetString("OpenNightban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启转发 的本地化字符串。
        /// </summary>
        public static string OpenTransmitButton {
            get {
                return ResourceManager.GetString("OpenTransmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超速轨迹 的本地化字符串。
        /// </summary>
        public static string OverSpeedTrack {
            get {
                return ResourceManager.GetString("OverSpeedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车主 的本地化字符串。
        /// </summary>
        public static string Owners {
            get {
                return ResourceManager.GetString("Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数配置有误! 的本地化字符串。
        /// </summary>
        public static string ParameterConfigurationError {
            get {
                return ResourceManager.GetString("ParameterConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待处理异常列表 的本地化字符串。
        /// </summary>
        public static string PendingListOfExceptions {
            get {
                return ResourceManager.GetString("PendingListOfExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提货点 的本地化字符串。
        /// </summary>
        public static string PickUpPoint {
            get {
                return ResourceManager.GetString("PickUpPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌 的本地化字符串。
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 的本地化字符串。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入地址信息 的本地化字符串。
        /// </summary>
        public static string Please_Enter_The_Address_Information {
            get {
                return ResourceManager.GetString("Please Enter The Address Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择用户！ 的本地化字符串。
        /// </summary>
        public static string PleaseChooseUserFirst {
            get {
                return ResourceManager.GetString("PleaseChooseUserFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入 的本地化字符串。
        /// </summary>
        public static string PleaseInput {
            get {
                return ResourceManager.GetString("PleaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入车代号并选择一条记录！ 的本地化字符串。
        /// </summary>
        public static string PleaseInputVehicleNameAndPickOne {
            get {
                return ResourceManager.GetString("PleaseInputVehicleNameAndPickOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择隶属单位 的本地化字符串。
        /// </summary>
        public static string PleaseSelectAffiliatedunits {
            get {
                return ResourceManager.GetString("PleaseSelectAffiliatedunits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择项！ 的本地化字符串。
        /// </summary>
        public static string PleaseSelectItem {
            get {
                return ResourceManager.GetString("PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多边形 的本地化字符串。
        /// </summary>
        public static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜在客户 的本地化字符串。
        /// </summary>
        public static string PotentialCustomer {
            get {
                return ResourceManager.GetString("PotentialCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主服务器IP地址或域名 的本地化字符串。
        /// </summary>
        public static string PrimaryServerIP {
            get {
                return ResourceManager.GetString("PrimaryServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理结果描述 的本地化字符串。
        /// </summary>
        public static string ProcessingResultDescription {
            get {
                return ResourceManager.GetString("ProcessingResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取中... 的本地化字符串。
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时异常 的本地化字符串。
        /// </summary>
        public static string RealTimeExceptions {
            get {
                return ResourceManager.GetString("RealTimeExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到车代号为{0}的{1}车辆信息！ 的本地化字符串。
        /// </summary>
        public static string RealTimeMonitoringSearchResult {
            get {
                return ResourceManager.GetString("RealTimeMonitoringSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货点 的本地化字符串。
        /// </summary>
        public static string ReceivePoint {
            get {
                return ResourceManager.GetString("ReceivePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形 的本地化字符串。
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复 的本地化字符串。
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复查岗 的本地化字符串。
        /// </summary>
        public static string ReplyInspection {
            get {
                return ResourceManager.GetString("ReplyInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码 的本地化字符串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车必须输入道路运输证号！ 的本地化字符串。
        /// </summary>
        public static string RoadransportNoError {
            get {
                return ResourceManager.GetString("RoadransportNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路线 的本地化字符串。
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测距 的本地化字符串。
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行驶 的本地化字符串。
        /// </summary>
        public static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废 的本地化字符串。
        /// </summary>
        public static string ScrapButton {
            get {
                return ResourceManager.GetString("ScrapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看经营范围 的本地化字符串。
        /// </summary>
        public static string SearchBusinessScope {
            get {
                return ResourceManager.GetString("SearchBusinessScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索(S) 的本地化字符串。
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询中... 的本地化字符串。
        /// </summary>
        public static string SearchLoding {
            get {
                return ResourceManager.GetString("SearchLoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看运输行业 的本地化字符串。
        /// </summary>
        public static string SearchTransportIndustry {
            get {
                return ResourceManager.GetString("SearchTransportIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择用户 的本地化字符串。
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择分配车辆 的本地化字符串。
        /// </summary>
        public static string SelectVehiclesToBeAllocated {
            get {
                return ResourceManager.GetString("SelectVehiclesToBeAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送配置 的本地化字符串。
        /// </summary>
        public static string SendParameter {
            get {
                return ResourceManager.GetString("SendParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器TCP端口 的本地化字符串。
        /// </summary>
        public static string ServerTCPPort {
            get {
                return ResourceManager.GetString("ServerTCPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示报警信息 的本地化字符串。
        /// </summary>
        public static string ShowAlarmInfo {
            get {
                return ResourceManager.GetString("ShowAlarmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示区域 的本地化字符串。
        /// </summary>
        public static string ShowArea {
            get {
                return ResourceManager.GetString("ShowArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示电子围栏 的本地化字符串。
        /// </summary>
        public static string ShowEFMarker {
            get {
                return ResourceManager.GetString("ShowEFMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示地标 的本地化字符串。
        /// </summary>
        public static string ShowMarker {
            get {
                return ResourceManager.GetString("ShowMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示卸料列表 的本地化字符串。
        /// </summary>
        public static string ShowPressureTable {
            get {
                return ResourceManager.GetString("ShowPressureTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示信号列表 的本地化字符串。
        /// </summary>
        public static string ShowSignalsList {
            get {
                return ResourceManager.GetString("ShowSignalsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示停车点列表 的本地化字符串。
        /// </summary>
        public static string ShowStopContentTable {
            get {
                return ResourceManager.GetString("ShowStopContentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示温度曲线图 的本地化字符串。
        /// </summary>
        public static string ShowTemperTable {
            get {
                return ResourceManager.GetString("ShowTemperTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SIM卡号 的本地化字符串。
        /// </summary>
        public static string SIMCode {
            get {
                return ResourceManager.GetString("SIMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南 的本地化字符串。
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 东南 的本地化字符串。
        /// </summary>
        public static string SouthEast {
            get {
                return ResourceManager.GetString("SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西南 的本地化字符串。
        /// </summary>
        public static string SouthWest {
            get {
                return ResourceManager.GetString("SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车 的本地化字符串。
        /// </summary>
        public static string StopStatus {
            get {
                return ResourceManager.GetString("StopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位分配 的本地化字符串。
        /// </summary>
        public static string StrucDistribution {
            get {
                return ResourceManager.GetString("StrucDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Struct {
            get {
                return ResourceManager.GetString("Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切回原用户 的本地化字符串。
        /// </summary>
        public static string SwitchToOriginalUser {
            get {
                return ResourceManager.GetString("SwitchToOriginalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换用户 的本地化字符串。
        /// </summary>
        public static string SwitchUserButton {
            get {
                return ResourceManager.GetString("SwitchUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步收货地址 的本地化字符串。
        /// </summary>
        public static string SynchroReceiveAddress {
            get {
                return ResourceManager.GetString("SynchroReceiveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增联系人 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_AddContact {
            get {
                return ResourceManager.GetString("TerminalSetting_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫类型 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_CallType {
            get {
                return ResourceManager.GetString("TerminalSetting_CallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼入 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_CallTypeIn {
            get {
                return ResourceManager.GetString("TerminalSetting_CallTypeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼入/呼出 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_CallTypeInAndOut {
            get {
                return ResourceManager.GetString("TerminalSetting_CallTypeInAndOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼出 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_CallTypeOut {
            get {
                return ResourceManager.GetString("TerminalSetting_CallTypeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空并新增联系人 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_ClearAndAddContact {
            get {
                return ResourceManager.GetString("TerminalSetting_ClearAndAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用单位 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_CompanyName {
            get {
                return ResourceManager.GetString("TerminalSetting_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Contact {
            get {
                return ResourceManager.GetString("TerminalSetting_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有联系人 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_DelAllContact {
            get {
                return ResourceManager.GetString("TerminalSetting_DelAllContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲劳驾驶预警差值（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_DifferenceOfFatigueDrivingTime {
            get {
                return ResourceManager.GetString("TerminalSetting_DifferenceOfFatigueDrivingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超速报警预警差值（km/h） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_DifferenceOfOverspeedValues {
            get {
                return ResourceManager.GetString("TerminalSetting_DifferenceOfOverspeedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改电话本 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_EditPhonebook {
            get {
                return ResourceManager.GetString("TerminalSetting_EditPhonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_EndTime {
            get {
                return ResourceManager.GetString("TerminalSetting_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端心跳发送间隔（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_HeartbeatInterval {
            get {
                return ResourceManager.GetString("TerminalSetting_HeartbeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置字段 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_KeyName {
            get {
                return ResourceManager.GetString("TerminalSetting_KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置汇报策略 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_LocationReportPolicy {
            get {
                return ResourceManager.GetString("TerminalSetting_LocationReportPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置汇报方案 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_LocationReportTrigger {
            get {
                return ResourceManager.GetString("TerminalSetting_LocationReportTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续驾驶时间门限（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_MaximumDrivingTime {
            get {
                return ResourceManager.GetString("TerminalSetting_MaximumDrivingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当天累计驾驶时间门限（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_MaximumDrivingTimeToday {
            get {
                return ResourceManager.GetString("TerminalSetting_MaximumDrivingTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高速度（km/h） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_MaximumSpeed {
            get {
                return ResourceManager.GetString("TerminalSetting_MaximumSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最长停车时间（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_MaximumStoppingTime {
            get {
                return ResourceManager.GetString("TerminalSetting_MaximumStoppingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小休息时间（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_MinimumBreakTime {
            get {
                return ResourceManager.GetString("TerminalSetting_MinimumBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超速持续时间（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_OverspeedCheckTime {
            get {
                return ResourceManager.GetString("TerminalSetting_OverspeedCheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_PlateNumber {
            get {
                return ResourceManager.GetString("TerminalSetting_PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数查看 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Query {
            get {
                return ResourceManager.GetString("TerminalSetting_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取设置 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_QuerySetting {
            get {
                return ResourceManager.GetString("TerminalSetting_QuerySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置类型 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_SettingType {
            get {
                return ResourceManager.GetString("TerminalSetting_SettingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_ShowPathOrRegion {
            get {
                return ResourceManager.GetString("TerminalSetting_ShowPathOrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_StartTime {
            get {
                return ResourceManager.GetString("TerminalSetting_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺省时间汇报间隔（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_StateRepotrInterval_General {
            get {
                return ResourceManager.GetString("TerminalSetting_StateRepotrInterval_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登录汇报间隔（秒） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_StateRepotrInterval_NotLoggedIn {
            get {
                return ResourceManager.GetString("TerminalSetting_StateRepotrInterval_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休眠时汇报时间间隔（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_StateRepotrInterval_Sleep {
            get {
                return ResourceManager.GetString("TerminalSetting_StateRepotrInterval_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急报警时汇报时间间隔（s） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_StateRepotrInterval_Urgent {
            get {
                return ResourceManager.GetString("TerminalSetting_StateRepotrInterval_Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Tel {
            get {
                return ResourceManager.GetString("TerminalSetting_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听电话号码 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_TelphoneNO {
            get {
                return ResourceManager.GetString("TerminalSetting_TelphoneNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端号 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_TerminalCode {
            get {
                return ResourceManager.GetString("TerminalSetting_TerminalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆里程表读数（km） 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_TotalODO {
            get {
                return ResourceManager.GetString("TerminalSetting_TotalODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知操作 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_None {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域设置追加 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_RegionSettings_Add {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_RegionSettings_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域设置删除 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_RegionSettings_Delete {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_RegionSettings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域设置更新 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_RegionSettings_Update {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_RegionSettings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径设置下发 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_RouteSettings_Add {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_RouteSettings_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除路径设置 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_RouteSettings_Delete {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_RouteSettings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话本设置 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_TelephoneBook {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_TelephoneBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端设置查询 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_TerminalSetup_Query {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_TerminalSetup_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端设置下发 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_TerminalSetup_Update {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_TerminalSetup_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本消息 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Type_TextMessage {
            get {
                return ResourceManager.GetString("TerminalSetting_Type_TextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数设定 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_Update {
            get {
                return ResourceManager.GetString("TerminalSetting_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下发设置 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_UpdateSetting {
            get {
                return ResourceManager.GetString("TerminalSetting_UpdateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段值 的本地化字符串。
        /// </summary>
        public static string TerminalSetting_ValueName {
            get {
                return ResourceManager.GetString("TerminalSetting_ValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间周期 的本地化字符串。
        /// </summary>
        public static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车必须选择运输行业！ 的本地化字符串。
        /// </summary>
        public static string TransportIndustryError {
            get {
                return ResourceManager.GetString("TransportIndustryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运管所 的本地化字符串。
        /// </summary>
        public static string TransportManagement {
            get {
                return ResourceManager.GetString("TransportManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险品车转发运管必须选择运管所！ 的本地化字符串。
        /// </summary>
        public static string TransportManagementError {
            get {
                return ResourceManager.GetString("TransportManagementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除终端绑定信息 的本地化字符串。
        /// </summary>
        public static string Unbind {
            get {
                return ResourceManager.GetString("Unbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑车辆 的本地化字符串。
        /// </summary>
        public static string UnBindVehicle {
            get {
                return ResourceManager.GetString("UnBindVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启用 的本地化字符串。
        /// </summary>
        public static string UnEnableButton {
            get {
                return ResourceManager.GetString("UnEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未结束 的本地化字符串。
        /// </summary>
        public static string UnFinished {
            get {
                return ResourceManager.GetString("UnFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string UserNamePlaceHolder {
            get {
                return ResourceManager.GetString("UserNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在用客户 的本地化字符串。
        /// </summary>
        public static string UsingCustomer {
            get {
                return ResourceManager.GetString("UsingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆基本信息 的本地化字符串。
        /// </summary>
        public static string VehicleBasicInfo {
            get {
                return ResourceManager.GetString("VehicleBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆分配 的本地化字符串。
        /// </summary>
        public static string VehicleDistribution {
            get {
                return ResourceManager.GetString("VehicleDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆异常信息 的本地化字符串。
        /// </summary>
        public static string VehicleExceptionInfo {
            get {
                return ResourceManager.GetString("VehicleExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆分配列表中已存在 的本地化字符串。
        /// </summary>
        public static string VehiclesDistributionListError {
            get {
                return ResourceManager.GetString("VehiclesDistributionListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆查询 的本地化字符串。
        /// </summary>
        public static string VehicleSearch {
            get {
                return ResourceManager.GetString("VehicleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器信息 的本地化字符串。
        /// </summary>
        public static string VehicleSensorInfo {
            get {
                return ResourceManager.GetString("VehicleSensorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音消息 的本地化字符串。
        /// </summary>
        public static string VoiceMessage {
            get {
                return ResourceManager.GetString("VoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎您！ 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎页 的本地化字符串。
        /// </summary>
        public static string WelcomePage {
            get {
                return ResourceManager.GetString("WelcomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西 的本地化字符串。
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年检预警 的本地化字符串。
        /// </summary>
        public static string YearsCheckAlarm {
            get {
                return ResourceManager.GetString("YearsCheckAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年检提示提前天数不能小于0！ 的本地化字符串。
        /// </summary>
        public static string YearsCheckTimeSpan {
            get {
                return ResourceManager.GetString("YearsCheckTimeSpan", resourceCulture);
            }
        }
    }
}
