//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asiatek.TMS.TerminalServicesNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TerminalServicesNS.TerminalServicesSoap")]
    public interface TerminalServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 terminalCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DealEmergencyAlarm", ReplyAction="*")]
        Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmResponse DealEmergencyAlarm(Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DealEmergencyAlarmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DealEmergencyAlarm", Namespace="http://tempuri.org/", Order=0)]
        public Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequestBody Body;
        
        public DealEmergencyAlarmRequest() {
        }
        
        public DealEmergencyAlarmRequest(Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DealEmergencyAlarmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string terminalCode;
        
        public DealEmergencyAlarmRequestBody() {
        }
        
        public DealEmergencyAlarmRequestBody(long ID, string terminalCode) {
            this.ID = ID;
            this.terminalCode = terminalCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DealEmergencyAlarmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DealEmergencyAlarmResponse", Namespace="http://tempuri.org/", Order=0)]
        public Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmResponseBody Body;
        
        public DealEmergencyAlarmResponse() {
        }
        
        public DealEmergencyAlarmResponse(Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DealEmergencyAlarmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DealEmergencyAlarmResult;
        
        public DealEmergencyAlarmResponseBody() {
        }
        
        public DealEmergencyAlarmResponseBody(int DealEmergencyAlarmResult) {
            this.DealEmergencyAlarmResult = DealEmergencyAlarmResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TerminalServicesSoapChannel : Asiatek.TMS.TerminalServicesNS.TerminalServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalServicesSoapClient : System.ServiceModel.ClientBase<Asiatek.TMS.TerminalServicesNS.TerminalServicesSoap>, Asiatek.TMS.TerminalServicesNS.TerminalServicesSoap {
        
        public TerminalServicesSoapClient() {
        }
        
        public TerminalServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmResponse Asiatek.TMS.TerminalServicesNS.TerminalServicesSoap.DealEmergencyAlarm(Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequest request) {
            return base.Channel.DealEmergencyAlarm(request);
        }
        
        public int DealEmergencyAlarm(long ID, string terminalCode) {
            Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequest inValue = new Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequest();
            inValue.Body = new Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.terminalCode = terminalCode;
            Asiatek.TMS.TerminalServicesNS.DealEmergencyAlarmResponse retVal = ((Asiatek.TMS.TerminalServicesNS.TerminalServicesSoap)(this)).DealEmergencyAlarm(inValue);
            return retVal.Body.DealEmergencyAlarmResult;
        }
    }
}
